# Generated by Django 5.0.4 on 2024-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=60)),
                ("phone", models.CharField(max_length=10)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
