# Generated by Django 5.0.4 on 2024-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
