# Generated by Django 5.0.4 on 2024-08-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_create_user_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="create_user",
        ),
    ]
